### ISSUE TITLE
bot parsing error?

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/zh-hant.javascript.info#15]
@iliakan 
It seems like there are some parsing errors of bot in #1 and #14 .
Could you please check on them? Thanks.

**Comment by iliakan** [comment]
You try to take an unassigned article, and it adds "...has meta information..." comment, but still adds you successfully?

Is that the correct behavior? If not, please tell me what exactly is going on.

Thanks!

**Comment by lenchen1112** [comment]
It seems like the bot was triggered twice.
In #1, I just leave title of `Data types` and first it left a thumb under my comment and then the bot added a comment with this error message.
And in #14 after the PR is sent, the bot left the error message directly under my PR.
However it seems like only happen with title `Data types` so we can close this issue first. I will keep watching and tell you once it happens again.

**Comment by iliakan** [comment]
Ok, if that happens again, please let me know, was the article somehow labeled before or not. 

If it was labeled already, then the bot acts correctly.
