### ISSUE TITLE
Join member

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/zh-hant.javascript.info#17]
Hi @iliakan,
Please help to join `arvin0731@gmail.com` as maintainer of this repo, which means join him into team `translate-zh-hant` cause we don't have permission to join outside member into it.
Many thanks.

**Comment by iliakan** [comment]
What's his github nick?

**Comment by iliakan** [comment]
Added ArvinH.

**Comment by lenchen1112** [comment]
@iliakan 
![螢幕快照 2019-08-27 下午2 37 37](https://user-images.githubusercontent.com/10217843/63746844-50775600-c8d8-11e9-8574-5e812c52c668.png)
seems like he is not a member of organization yet.

**Comment by iliakan** [comment]
Whoops, he is now!
