### ISSUE TITLE
permission about team translate-zh-hant

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/zh-hant.javascript.info#2]
@iliakan 
Sorry that I accidentally change permission of team `translate-zh-hant` about this repository to be `write` only. Could you help to set permission back to `admin`?
Many thanks.

**Comment by iliakan** [comment]
I think it was write by default. You need to elevate it to admin?

**Comment by lenchen1112** [comment]
Originally it's admin of this repository.

**Comment by iliakan** [comment]
Permissions are managed at Team level. Your team is Admin now! 🎉
