### ISSUE TITLE
Settings has been changed to default

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/zh-hant.javascript.info#23]
@iliakan
We'd like to know is there any script that will revert our setting back to default cause we found that our settings was changed without notice.

We opened wiki and use squash merge in our repo but it was set back to default.
![螢幕快照 2019-08-28 下午6 01 08](https://user-images.githubusercontent.com/10217843/63846289-11bbcb80-c9be-11e9-9121-e6fbdb8139bf.png)

![螢幕快照 2019-08-28 下午6 01 02](https://user-images.githubusercontent.com/10217843/63846287-11bbcb80-c9be-11e9-8831-1b69061e2b09.png)

Do you have any idea about this?

**Comment by iliakan** [comment]
That's because of my script, it changed the settings to default.

Are you sure squash merge is a good idea?

**Comment by lenchen1112** [comment]
Yes, we'd like to use squash merge to keep the commit history cleaner. Is it possible to remain our changes of settings?

**Comment by iliakan** [comment]
Sure, it is. I added this special setting to the script. 

The script is meant so simplify stuff such as adding maintainers, re-creating the progress issue etc, it stores all settings in its config and applies them.

These are the current repo settings:
```json
{
      has_projects:       false,
      has_wiki:           false,
      homepage:       `https://javascript.info`,
      allow_merge_commit: true,
      allow_squash_merge: true,
      allow_rebase_merge: false
}
```

I can either tweak the default settings for your translation or not use script at all.

**Comment by lenchen1112** [comment]
Thanks, that will be great :)
And if we'd like to change configurations, just open issue to you for modifying corresponding fields?

**Comment by iliakan** [comment]
I think, it's better to add repo settings to script, yes.
