### ISSUE TITLE
Pull Panda

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/zh-hant.javascript.info#26]
@ArvinH requested an install. I approved it, but does it need some settings?

Maybe I should have refused to install it?

**Comment by ArvinH** [comment]
Hi @iliakan, thanks for your approval.
Yes, it does need some settings but I only authorize pullreminder to our own slack channel and this specific repo & members (not all organization), and I can do that by myself. It should be fine.

Do you have any concerns about this? I just want to use this for reminding us to calibrate contents.

**Comment by iliakan** [comment]
So, no other actions from my side are needed?

I have no other concerns =)

**Comment by ArvinH** [comment]
Yup, no other actions are needed from your side 👍 Thanks!
