### ISSUE TITLE
request to change settings

### ISSUE THREAD

**Issue by lenchen1112** [javascript-tutorial/zh-hant.javascript.info#31]
hi @iliakan 
We'd like to change settings of wiki and ordinary merge as follow:

```js
has_wiki:           true,
allow_merge_commit: false,
```

so the entire setting of our repo should be:
```js
{
  has_projects:       false,
  has_wiki:           true,
  homepage:           `https://javascript.info`,
  allow_merge_commit: false,
  allow_squash_merge: true,
  allow_rebase_merge: false
}
```

Please help to modify them.
Many thanks.

**Comment by iliakan** [comment]
Settings updated!

**Comment by iliakan** [comment]
I see you're using custom labels, such as "proofreading needed".
You got familiar with the current translate bot, didn't you? Does it help, should it stay enabled?

**Comment by lenchen1112** [comment]
We use "proofreading needed" label to mark a PR needs someone to calibrate sentence only. There is no any other usage with bot. Will it affect bot operations?

**Comment by iliakan** [comment]
The bot helps with the flow to ensure double review of each article.

Here's what it does:
http://javascript.info/translate/bot
