### ISSUE TITLE
The selected translation title does not match the content, and the translation has been completed 選擇的翻譯標題與內容不相符，且該篇翻譯已被完成了

### ISSUE THREAD

**Issue by oooooo** [javascript-tutorial/zh-hant.javascript.info#73]
繁體中文翻譯進度 issue (Chinese Traditional Translation Progress) 中
標題 "Function expressions"  ( in `The JavaScript language > JavaScript Fundamentals >`) 在文件中為 "15-function-expressions-arrows" 而且有翻譯過了，請問該如何下一步呢？

**Comment by lenchen1112** [comment]
@oooooo 看起來是 tracking bot 有點問題，我來看一下是為什麼

**Comment by lenchen1112** [comment]
看來是上次 sync 時 upstream 修改過檔案標題，所以 tracking bot 直接失效，我手動改一下 tracking issue，再麻煩你認領其它份，謝謝
